apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-config
  namespace: default
  labels:
    app.kubernetes.io/name: pipeline
    app.kubernetes.io/instance: pipeline
data:
  config.toml: |
    # Configuration file running Pipeline locally

    title = "Configuration for Pipeline"

    debug = true

    [nats]
    servers = ["nats://nats.default:4222"]

    [collect]
    host = "localhost"
    port = "50051"
