---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-validate
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pipeline-validate
      app.kubernetes.io/instance: pipeline-validate
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pipeline-validate
        app.kubernetes.io/instance: pipeline-validate
    spec:
      restartPolicy: Always
      containers:
        - name: pipeline-validate
          image: ko://github.com/opisvigilant/futura/pipeline
          args: ["validate"]
          ports:
            - containerPort: 50052 # Added container port 50052
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests: {}
          volumeMounts:
            - name: configuration
              mountPath: /opt/pipeline/config.toml
              subPath: config.toml
      volumes:
        - name: configuration
          configMap:
            name: pipeline-config
---
apiVersion: v1
kind: Service
metadata:
  name: pipeline-validate
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: pipeline-validate
    app.kubernetes.io/instance: pipeline-validate
  ports:
    - protocol: TCP
      port: 50052 # Service port
      targetPort: 50052 # Container port
  type: ClusterIP
