---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pipeline
      app.kubernetes.io/instance: pipeline
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pipeline
        app.kubernetes.io/instance: pipeline
    spec:
      restartPolicy: Always
      containers:
        - name: pipeline
          image: ko://github.com/opisvigilant/futura/pipeline
          args: ["collect"]
          ports:
            - containerPort: 50051 # Added container port 50051
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests: {}
          volumeMounts:
            - name: configuration
              mountPath: /opt/pipeline/config.toml
              subPath: config.toml
      volumes:
        - name: configuration
          configMap:
            name: pipeline-config
---
apiVersion: v1
kind: Service
metadata:
  name: pipeline
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: pipeline
    app.kubernetes.io/instance: pipeline
  ports:
    - protocol: TCP
      port: 50051 # Service port
      targetPort: 50051 # Container port
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-config
  namespace: default
  labels:
    app.kubernetes.io/name: pipeline
    app.kubernetes.io/instance: pipeline
data:
  config.toml: |
    # Configuration file running Pipeline locally

    title = "Configuration for Pipeline"

    debug = true

    [nats]
    servers = ["nats://nats.default:4222"]

    [collect]
    host = "0.0.0.0"
    port = "50051"
