---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pipeline
      app.kubernetes.io/instance: pipeline
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pipeline
        app.kubernetes.io/instance: pipeline
    spec:
      restartPolicy: Always
      serviceAccountName: pipeline
      hostNetwork: true
      containers:
        - name: pipeline
          image: ko://github.com/opisvigilant/futura/pipeline
          args: ["collect"]
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests: {}
          volumeMounts:
            - name: configuration
              mountPath: /opt/pipeline/config.toml
              subPath: config.toml
      volumes:
        - name: configuration
          configMap:
            name: pipeline-config
