---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-collect
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pipeline-collect
      app.kubernetes.io/instance: pipeline-collect
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pipeline-collect
        app.kubernetes.io/instance: pipeline-collect
    spec:
      restartPolicy: Always
      containers:
        - name: pipeline-collect
          image: ko://github.com/opisvigilant/futura/pipeline
          args: ["collect"]
          ports:
            - containerPort: 50051 # Added container port 50051
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests: {}
          volumeMounts:
            - name: configuration
              mountPath: /opt/pipeline/config.toml
              subPath: config.toml
      volumes:
        - name: configuration
          configMap:
            name: pipeline-config
---
apiVersion: v1
kind: Service
metadata:
  name: pipeline-collect
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: pipeline-collect
    app.kubernetes.io/instance: pipeline-collect
  ports:
    - protocol: TCP
      port: 50051 # Service port
      targetPort: 50051 # Container port
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-config
  namespace: default
  labels:
    app.kubernetes.io/name: pipeline
    app.kubernetes.io/instance: pipeline
data:
  config.toml: |
    [redis]
    servers = ["host.docker.internal:6379"]
    namespace = "api_keys"

    [kafka]
    brokers = ["host.docker.internal:9092"]

    [collect]
    endpoint = ":50051"

    [log]
    level = "debug"
