syntax = "proto3";

import "telemetry/events.proto";
import "telemetry/cluster.proto";
import "telemetry/stats.proto";
import "telemetry/ebpf.proto";

package collect;

option go_package = "github.com/opisvigilant/futura/proto/gen/collect;collect";

service CollectService {
  rpc SendEvents(telemetry.KubernetesEventBatch) returns (CollectAck);
  rpc SendClusterObjects(telemetry.KubernetesClusterObjectBatch)
      returns (CollectAck);
  rpc SendKubeletMetrics(telemetry.KubernetesKubeletStats) returns (CollectAck);
  rpc SendEBPFMetrics(telemetry.EBPFMetricsBatch) returns (CollectAck);
}

message CollectAck {
  string status = 1;
  string message = 2;
}