syntax = "proto3";

package collect;

option go_package = "github.com/opisvigilant/futura/proto/gen/collect;collect";

import "telemetry/events.proto";
import "telemetry/cluster.proto";
import "telemetry/stats.proto";
import "telemetry/ebpf.proto";

service CollectService {
  rpc CollectEvents(telemetry.KubernetesEventBatch) returns (CollectAck);
  rpc CollectClusterObjects(telemetry.KubernetesClusterObjectBatch)
      returns (CollectAck);
  rpc CollectKubeletMetrics(telemetry.KubernetesKubeletStats)
      returns (CollectAck);
  rpc CollectEBPFMetrics(telemetry.EBPFMetricsBatch) returns (CollectAck);
}

message CollectAck {
  string status = 1;
  string message = 2;
}