// Code generated by bpf2go; DO NOT EDIT.
//go:build linux

package memory_tracker

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type memory_trackerAllocInfo struct {
	_         structs.HostLayout
	Size      uint64
	Timestamp uint64
	CgroupId  uint64
	Pid       uint32
	StackId   uint32
}

type memory_trackerGcMetrics struct {
	_              structs.HostLayout
	GcCount        uint64
	GcTimeNs       uint64
	BytesCollected uint64
	LastGcTime     uint64
}

type memory_trackerMemoryMetrics struct {
	_               structs.HostLayout
	AllocCount      uint64
	FreeCount       uint64
	BytesAllocated  uint64
	BytesFreed      uint64
	NetAllocated    uint64
	SmallAllocs     uint64
	MediumAllocs    uint64
	LargeAllocs     uint64
	HugeAllocs      uint64
	PageFaults      uint64
	MajorPageFaults uint64
	LastUpdate      uint64
}

// loadMemory_tracker returns the embedded CollectionSpec for memory_tracker.
func loadMemory_tracker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Memory_trackerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load memory_tracker: %w", err)
	}

	return spec, err
}

// loadMemory_trackerObjects loads memory_tracker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*memory_trackerObjects
//	*memory_trackerPrograms
//	*memory_trackerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadMemory_trackerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadMemory_tracker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// memory_trackerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type memory_trackerSpecs struct {
	memory_trackerProgramSpecs
	memory_trackerMapSpecs
	memory_trackerVariableSpecs
}

// memory_trackerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type memory_trackerProgramSpecs struct {
	PeriodicLeakCheck *ebpf.ProgramSpec `ebpf:"periodic_leak_check"`
	TraceFree         *ebpf.ProgramSpec `ebpf:"trace_free"`
	TraceGoGcStart    *ebpf.ProgramSpec `ebpf:"trace_go_gc_start"`
	TraceKfree        *ebpf.ProgramSpec `ebpf:"trace_kfree"`
	TraceKmalloc      *ebpf.ProgramSpec `ebpf:"trace_kmalloc"`
	TraceMalloc       *ebpf.ProgramSpec `ebpf:"trace_malloc"`
	TraceMallocRet    *ebpf.ProgramSpec `ebpf:"trace_malloc_ret"`
}

// memory_trackerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type memory_trackerMapSpecs struct {
	ActiveAllocs     *ebpf.MapSpec `ebpf:"active_allocs"`
	GcMetricsMap     *ebpf.MapSpec `ebpf:"gc_metrics_map"`
	LeakCandidates   *ebpf.MapSpec `ebpf:"leak_candidates"`
	MemoryEvents     *ebpf.MapSpec `ebpf:"memory_events"`
	MemoryMetricsMap *ebpf.MapSpec `ebpf:"memory_metrics_map"`
	StackTraces      *ebpf.MapSpec `ebpf:"stack_traces"`
}

// memory_trackerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type memory_trackerVariableSpecs struct {
}

// memory_trackerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadMemory_trackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type memory_trackerObjects struct {
	memory_trackerPrograms
	memory_trackerMaps
	memory_trackerVariables
}

func (o *memory_trackerObjects) Close() error {
	return _Memory_trackerClose(
		&o.memory_trackerPrograms,
		&o.memory_trackerMaps,
	)
}

// memory_trackerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadMemory_trackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type memory_trackerMaps struct {
	ActiveAllocs     *ebpf.Map `ebpf:"active_allocs"`
	GcMetricsMap     *ebpf.Map `ebpf:"gc_metrics_map"`
	LeakCandidates   *ebpf.Map `ebpf:"leak_candidates"`
	MemoryEvents     *ebpf.Map `ebpf:"memory_events"`
	MemoryMetricsMap *ebpf.Map `ebpf:"memory_metrics_map"`
	StackTraces      *ebpf.Map `ebpf:"stack_traces"`
}

func (m *memory_trackerMaps) Close() error {
	return _Memory_trackerClose(
		m.ActiveAllocs,
		m.GcMetricsMap,
		m.LeakCandidates,
		m.MemoryEvents,
		m.MemoryMetricsMap,
		m.StackTraces,
	)
}

// memory_trackerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadMemory_trackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type memory_trackerVariables struct {
}

// memory_trackerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadMemory_trackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type memory_trackerPrograms struct {
	PeriodicLeakCheck *ebpf.Program `ebpf:"periodic_leak_check"`
	TraceFree         *ebpf.Program `ebpf:"trace_free"`
	TraceGoGcStart    *ebpf.Program `ebpf:"trace_go_gc_start"`
	TraceKfree        *ebpf.Program `ebpf:"trace_kfree"`
	TraceKmalloc      *ebpf.Program `ebpf:"trace_kmalloc"`
	TraceMalloc       *ebpf.Program `ebpf:"trace_malloc"`
	TraceMallocRet    *ebpf.Program `ebpf:"trace_malloc_ret"`
}

func (p *memory_trackerPrograms) Close() error {
	return _Memory_trackerClose(
		p.PeriodicLeakCheck,
		p.TraceFree,
		p.TraceGoGcStart,
		p.TraceKfree,
		p.TraceKmalloc,
		p.TraceMalloc,
		p.TraceMallocRet,
	)
}

func _Memory_trackerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed memory_tracker_bpf.o
var _Memory_trackerBytes []byte
