// Code generated by bpf2go; DO NOT EDIT.
//go:build linux

package security_monitor

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type security_monitorNetworkConnection struct {
	_                structs.HostLayout
	SrcIp            uint32
	DstIp            uint32
	SrcPort          uint16
	DstPort          uint16
	Protocol         uint8
	_                [3]byte
	Timestamp        uint64
	BytesTransferred uint64
	IsSuspicious     uint8
	_                [7]byte
	CgroupId         uint64
}

type security_monitorProcessInfo struct {
	_            structs.HostLayout
	Pid          uint32
	Ppid         uint32
	Uid          uint32
	Gid          uint32
	StartTime    uint64
	Comm         [16]int8
	Filename     [256]int8
	IsSuspicious uint8
	_            [7]byte
	CgroupId     uint64
}

type security_monitorSecurityMetrics struct {
	_                           structs.HostLayout
	TotalSyscalls               uint64
	SuspiciousSyscalls          uint64
	PrivilegeEscalationAttempts uint64
	SyscallRateViolations       uint64
	MemoryViolations            uint64
	CpuViolations               uint64
	FdViolations                uint64
	ProcessViolations           uint64
	SuspiciousConnections       uint64
	BlockedConnections          uint64
	PortScanAttempts            uint64
	NewProcesses                uint64
	SuspiciousProcesses         uint64
	SetuidExecutions            uint64
	ContainerEscapeAttempts     uint64
	UnauthorizedFileAccess      uint64
	SensitiveFileAccess         uint64
	SystemFileModifications     uint64
	LastUpdate                  uint64
}

type security_monitorSyscallStats struct {
	_            structs.HostLayout
	Count        uint64
	LastSeen     uint64
	AvgFrequency uint64
	IsSuspicious uint8
	_            [7]byte
}

// loadSecurity_monitor returns the embedded CollectionSpec for security_monitor.
func loadSecurity_monitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Security_monitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load security_monitor: %w", err)
	}

	return spec, err
}

// loadSecurity_monitorObjects loads security_monitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*security_monitorObjects
//	*security_monitorPrograms
//	*security_monitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSecurity_monitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSecurity_monitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// security_monitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type security_monitorSpecs struct {
	security_monitorProgramSpecs
	security_monitorMapSpecs
	security_monitorVariableSpecs
}

// security_monitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type security_monitorProgramSpecs struct {
	TraceFileAccess     *ebpf.ProgramSpec `ebpf:"trace_file_access"`
	TraceMemoryPressure *ebpf.ProgramSpec `ebpf:"trace_memory_pressure"`
	TraceOomEvent       *ebpf.ProgramSpec `ebpf:"trace_oom_event"`
	TraceProcessExec    *ebpf.ProgramSpec `ebpf:"trace_process_exec"`
	TraceSysEnter       *ebpf.ProgramSpec `ebpf:"trace_sys_enter"`
	TraceTcpConnect     *ebpf.ProgramSpec `ebpf:"trace_tcp_connect"`
}

// security_monitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type security_monitorMapSpecs struct {
	NetworkConnectionsMap *ebpf.MapSpec `ebpf:"network_connections_map"`
	ProcessMap            *ebpf.MapSpec `ebpf:"process_map"`
	SecurityEvents        *ebpf.MapSpec `ebpf:"security_events"`
	SecurityMetricsMap    *ebpf.MapSpec `ebpf:"security_metrics_map"`
	SensitivePathsMap     *ebpf.MapSpec `ebpf:"sensitive_paths_map"`
	SyscallAllowlist      *ebpf.MapSpec `ebpf:"syscall_allowlist"`
	SyscallStatsMap       *ebpf.MapSpec `ebpf:"syscall_stats_map"`
}

// security_monitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type security_monitorVariableSpecs struct {
}

// security_monitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSecurity_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type security_monitorObjects struct {
	security_monitorPrograms
	security_monitorMaps
	security_monitorVariables
}

func (o *security_monitorObjects) Close() error {
	return _Security_monitorClose(
		&o.security_monitorPrograms,
		&o.security_monitorMaps,
	)
}

// security_monitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSecurity_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type security_monitorMaps struct {
	NetworkConnectionsMap *ebpf.Map `ebpf:"network_connections_map"`
	ProcessMap            *ebpf.Map `ebpf:"process_map"`
	SecurityEvents        *ebpf.Map `ebpf:"security_events"`
	SecurityMetricsMap    *ebpf.Map `ebpf:"security_metrics_map"`
	SensitivePathsMap     *ebpf.Map `ebpf:"sensitive_paths_map"`
	SyscallAllowlist      *ebpf.Map `ebpf:"syscall_allowlist"`
	SyscallStatsMap       *ebpf.Map `ebpf:"syscall_stats_map"`
}

func (m *security_monitorMaps) Close() error {
	return _Security_monitorClose(
		m.NetworkConnectionsMap,
		m.ProcessMap,
		m.SecurityEvents,
		m.SecurityMetricsMap,
		m.SensitivePathsMap,
		m.SyscallAllowlist,
		m.SyscallStatsMap,
	)
}

// security_monitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSecurity_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type security_monitorVariables struct {
}

// security_monitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSecurity_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type security_monitorPrograms struct {
	TraceFileAccess     *ebpf.Program `ebpf:"trace_file_access"`
	TraceMemoryPressure *ebpf.Program `ebpf:"trace_memory_pressure"`
	TraceOomEvent       *ebpf.Program `ebpf:"trace_oom_event"`
	TraceProcessExec    *ebpf.Program `ebpf:"trace_process_exec"`
	TraceSysEnter       *ebpf.Program `ebpf:"trace_sys_enter"`
	TraceTcpConnect     *ebpf.Program `ebpf:"trace_tcp_connect"`
}

func (p *security_monitorPrograms) Close() error {
	return _Security_monitorClose(
		p.TraceFileAccess,
		p.TraceMemoryPressure,
		p.TraceOomEvent,
		p.TraceProcessExec,
		p.TraceSysEnter,
		p.TraceTcpConnect,
	)
}

func _Security_monitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed security_monitor_bpf.o
var _Security_monitorBytes []byte
