{{- if .Values.collect.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "futura-pipeline.fullname" . }}-collect
  labels:
    {{- include "futura-pipeline.labels" . | nindent 4 }}
    app.kubernetes.io/component: collect
spec:
  type: {{ .Values.collect.service.type }}
  ports:
    - port: {{ .Values.collect.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "futura-pipeline.collectSelectorLabels" . | nindent 4 }}
{{- end }}
