.PHONY: dev
dev: install 	
	bun run dev

.PHONY: build
build: install 
	bun run build

.PHONY: preview
preview: install 
	bun run preview

.PHONY: lint
lint: 
	bun run lint

.PHONY: install
install:
	bun install