.PHONY: install dev
dev: ## Run bun 	
	bun run dev

.PHONY: install build
build: ## Run bun 
	bun run build

.PHONY: install preview
preview: ## Run bun 
	bun run preview

.PHONY: lint
lint: ## Run bun 
	bun run lint

.PHONY: install
install:
	bun install