services:
  postgres:
    image: postgres:15.4
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: futura
      POSTGRES_MULTIPLE_DATABASES: unleash
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./apis/scritps/init-dbs.sh:/docker-entrypoint-initdb.d/init-dbs.sh
      - ./data/postgres:/var/lib/postgresql/data

  unleash:
    image: unleashorg/unleash-server:latest
    container_name: unleash
    ports:
      - "4242:4242"
    environment:
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
      DATABASE_NAME: "unleash"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "postgres"
      DATABASE_SCHEMA: "public"
      # Disable SSL for database connections.
      DATABASE_SSL: "false"
      # Changing log levels:
      LOG_LEVEL: "warn"
      INIT_FRONTEND_API_TOKENS: "default:development.unleash-insecure-frontend-api-token"
      # The default API token is insecure and should not be used in production.
      INIT_CLIENT_API_TOKENS: "default:development.unleash-insecure-api-token"
      CHECK_VERSION: false
      SEND_TELEMETRY: false
    depends_on:
      - postgres
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4242/health || exit 1
      interval: 1s
      timeout: 1m
      retries: 5
      start_period: 15s

  redis:
    image: redis:8.0.3
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    restart: unless-stopped
    profiles:
      - dev-tools

  clickhouse:
    image: clickhouse/clickhouse-server:25.6-alpine
    container_name: clickhouse
    environment:
      CLICKHOUSE_DB: events
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: password
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse

  kafka1:
    image: apache/kafka:4.0.1-rc0
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka1:9092,CONTROLLER://kafka1:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka1:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      CLUSTER_ID: "EmptNWtoR4GGWx-BH6nGLQ"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
    volumes:
      - ./data/kafka1:/var/lib/kafka/data

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: kafka-cluster-ui
    ports:
      - "9080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092
    depends_on:
      - kafka1
    profiles:
      - dev-tools

volumes:
  db:

networks:
  default:
    name: kind
    external: true
