// Code generated by bpf2go; DO NOT EDIT.
//go:build linux

package cpu_tracker

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type cpu_trackerCpuMetrics struct {
	_                   structs.HostLayout
	UserTimeNs          uint64
	SystemTimeNs        uint64
	ContextSwitches     uint64
	VoluntarySwitches   uint64
	InvoluntarySwitches uint64
	RunqueueLatencySum  uint64
	RunqueueSamples     uint64
	ActiveThreads       uint32
	BlockedThreads      uint32
	LastUpdate          uint64
}

// loadCpu_tracker returns the embedded CollectionSpec for cpu_tracker.
func loadCpu_tracker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Cpu_trackerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load cpu_tracker: %w", err)
	}

	return spec, err
}

// loadCpu_trackerObjects loads cpu_tracker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*cpu_trackerObjects
//	*cpu_trackerPrograms
//	*cpu_trackerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCpu_trackerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCpu_tracker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// cpu_trackerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cpu_trackerSpecs struct {
	cpu_trackerProgramSpecs
	cpu_trackerMapSpecs
	cpu_trackerVariableSpecs
}

// cpu_trackerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cpu_trackerProgramSpecs struct {
	CpuProfile       *ebpf.ProgramSpec `ebpf:"cpu_profile"`
	TraceProcessExit *ebpf.ProgramSpec `ebpf:"trace_process_exit"`
	TraceSchedSwitch *ebpf.ProgramSpec `ebpf:"trace_sched_switch"`
	TraceSchedWakeup *ebpf.ProgramSpec `ebpf:"trace_sched_wakeup"`
}

// cpu_trackerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cpu_trackerMapSpecs struct {
	CpuMetricsMap      *ebpf.MapSpec `ebpf:"cpu_metrics_map"`
	ProcessSwitchTimes *ebpf.MapSpec `ebpf:"process_switch_times"`
	StackTraces        *ebpf.MapSpec `ebpf:"stack_traces"`
}

// cpu_trackerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cpu_trackerVariableSpecs struct {
}

// cpu_trackerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCpu_trackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type cpu_trackerObjects struct {
	cpu_trackerPrograms
	cpu_trackerMaps
	cpu_trackerVariables
}

func (o *cpu_trackerObjects) Close() error {
	return _Cpu_trackerClose(
		&o.cpu_trackerPrograms,
		&o.cpu_trackerMaps,
	)
}

// cpu_trackerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCpu_trackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type cpu_trackerMaps struct {
	CpuMetricsMap      *ebpf.Map `ebpf:"cpu_metrics_map"`
	ProcessSwitchTimes *ebpf.Map `ebpf:"process_switch_times"`
	StackTraces        *ebpf.Map `ebpf:"stack_traces"`
}

func (m *cpu_trackerMaps) Close() error {
	return _Cpu_trackerClose(
		m.CpuMetricsMap,
		m.ProcessSwitchTimes,
		m.StackTraces,
	)
}

// cpu_trackerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCpu_trackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type cpu_trackerVariables struct {
}

// cpu_trackerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCpu_trackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type cpu_trackerPrograms struct {
	CpuProfile       *ebpf.Program `ebpf:"cpu_profile"`
	TraceProcessExit *ebpf.Program `ebpf:"trace_process_exit"`
	TraceSchedSwitch *ebpf.Program `ebpf:"trace_sched_switch"`
	TraceSchedWakeup *ebpf.Program `ebpf:"trace_sched_wakeup"`
}

func (p *cpu_trackerPrograms) Close() error {
	return _Cpu_trackerClose(
		p.CpuProfile,
		p.TraceProcessExit,
		p.TraceSchedSwitch,
		p.TraceSchedWakeup,
	)
}

func _Cpu_trackerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cpu_tracker_bpf.o
var _Cpu_trackerBytes []byte
