load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "pod",
    srcs = ["pods.go"],
    importpath = "github.com/opisvigilant/futura/watcher/internal/cluster/pod",
    visibility = ["//watcher:__subpackages__"],
    deps = [
        "//proto/gen/telemetry",
        "//watcher/internal/cluster/constants",
        "//watcher/internal/cluster/container",
        "//watcher/internal/cluster/gvk",
        "//watcher/internal/cluster/metadata",
        "//watcher/internal/cluster/service",
        "//watcher/utils",
        "@com_github_rs_zerolog//log",
        "@io_k8s_api//apps/v1:apps",
        "@io_k8s_api//batch/v1:batch",
        "@io_k8s_api//core/v1:core",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_client_go//tools/cache",
        "@io_opentelemetry_go_otel//semconv/v1.6.1:v1_6_1",
        "@org_golang_google_protobuf//types/known/timestamppb",
    ],
)
