# Configuration file running Watcher locally
[collect]
endpoint = "localhost:50051"
apiKey = "df9166bbacd761c74aecc50bb7a902342dd61a1de84551e253f7133154947d88"

[kubernetes]
authType = "kubeConfig" # required, valid values are `none`, `serviceAccount`, `kubeConfig`
kubeContextName = "kind-dev-cluster"
namespaces = []
distribution = "kubernetes" # either openshift or kubernetes
collectionInterval = "" # in seconds, default is 10
metadataCollectionInterval = "" # in minutes, default is 5
leaseName = "futura" # required
leaseNamespace = "default" # required
leaseDuration = "" # in seconds, default is 15
renewDeadline = "" # in seconds, default is 10
retryPeriod = "" # in seconds, default is 2

[log]
level = "debug" # valid values: debug, info, warn, error