# Configuration file running Norman locally

title = "Configuration for Watcher"

debug = true
enablePprof = true
nodeName = "localhost"
tag = "v0.0.1"

[handler]
[handler.console]
color = true

[handler.webhook]
url = "http://localhost:8080/events"
batchSize = 1000
cert = ""
tlsSkip = true
