# Configuration file running Norman locally

title = "Configuration for Watcher"

debug = true
nodeName = "localhost"
tag = "v0.0.1"

[collect]
host = "localhost"
port = "50051"

[kubernetes]
inCluster = false # true when the agent is deployed within the kubernetes cluster