// Code generated by bpf2go; DO NOT EDIT.
//go:build linux

package rps

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadRps returns the embedded CollectionSpec for rps.
func loadRps() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RpsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load rps: %w", err)
	}

	return spec, err
}

// loadRpsObjects loads rps and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*rpsObjects
//	*rpsPrograms
//	*rpsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRpsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadRps()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// rpsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rpsSpecs struct {
	rpsProgramSpecs
	rpsMapSpecs
	rpsVariableSpecs
}

// rpsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rpsProgramSpecs struct {
	TraceSockState *ebpf.ProgramSpec `ebpf:"trace_sock_state"`
}

// rpsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rpsMapSpecs struct {
	Rps *ebpf.MapSpec `ebpf:"rps"`
}

// rpsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rpsVariableSpecs struct {
}

// rpsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRpsObjects or ebpf.CollectionSpec.LoadAndAssign.
type rpsObjects struct {
	rpsPrograms
	rpsMaps
	rpsVariables
}

func (o *rpsObjects) Close() error {
	return _RpsClose(
		&o.rpsPrograms,
		&o.rpsMaps,
	)
}

// rpsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRpsObjects or ebpf.CollectionSpec.LoadAndAssign.
type rpsMaps struct {
	Rps *ebpf.Map `ebpf:"rps"`
}

func (m *rpsMaps) Close() error {
	return _RpsClose(
		m.Rps,
	)
}

// rpsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadRpsObjects or ebpf.CollectionSpec.LoadAndAssign.
type rpsVariables struct {
}

// rpsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRpsObjects or ebpf.CollectionSpec.LoadAndAssign.
type rpsPrograms struct {
	TraceSockState *ebpf.Program `ebpf:"trace_sock_state"`
}

func (p *rpsPrograms) Close() error {
	return _RpsClose(
		p.TraceSockState,
	)
}

func _RpsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed rps_bpf.o
var _RpsBytes []byte
