load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "cluster",
    srcs = [
        "cluster.go",
        "watcher.go",
    ],
    importpath = "github.com/opisvigilant/futura/watcher/internal/cluster",
    visibility = ["//watcher:__subpackages__"],
    deps = [
        "//watcher/internal/cluster/collection",
        "//watcher/internal/cluster/cronjob",
        "//watcher/internal/cluster/daemonset",
        "//watcher/internal/cluster/deployment",
        "//watcher/internal/cluster/gvk",
        "//watcher/internal/cluster/hpa",
        "//watcher/internal/cluster/jobs",
        "//watcher/internal/cluster/metadata",
        "//watcher/internal/cluster/namespace",
        "//watcher/internal/cluster/node",
        "//watcher/internal/cluster/pod",
        "//watcher/internal/cluster/replicaset",
        "//watcher/internal/cluster/replicationcontroller",
        "//watcher/internal/cluster/service",
        "//watcher/internal/cluster/statefulset",
        "//watcher/internal/config",
        "//watcher/internal/sender",
        "//watcher/pkg/kubernetes",
        "@com_github_openshift_client_go//quota/clientset/versioned",
        "@com_github_openshift_client_go//quota/informers/externalversions",
        "@com_github_rs_zerolog//log",
        "@io_k8s_api//apps/v1:apps",
        "@io_k8s_api//autoscaling/v2:autoscaling",
        "@io_k8s_api//batch/v1:batch",
        "@io_k8s_api//core/v1:core",
        "@io_k8s_apimachinery//pkg/api/errors",
        "@io_k8s_apimachinery//pkg/runtime/schema",
        "@io_k8s_client_go//informers",
        "@io_k8s_client_go//kubernetes",
        "@io_k8s_client_go//tools/cache",
    ],
)
