load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "server",
    srcs = ["server.go"],
    importpath = "github.com/opisvigilant/futura/analytics/internal/server",
    visibility = ["//analytics:__subpackages__"],
    deps = [
        "//analytics/internal/config",
        "//proto/gen/analytics",
        "//proto/gen/telemetry",
        "@com_github_clickhouse_clickhouse_go_v2//:clickhouse-go",
        "@com_github_clickhouse_clickhouse_go_v2//lib/driver",
        "@com_github_rs_zerolog//log",
    ],
)

go_test(
    name = "server_test",
    srcs = ["server_test.go"],
    embed = [":server"],
    deps = [
        "//analytics/internal/config",
        "//proto/gen/analytics",
        "@com_github_clickhouse_clickhouse_go_v2//:clickhouse-go",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
