load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "events",
    srcs = ["events.go"],
    importpath = "github.com/opisvigilant/futura/watcher/internal/events",
    visibility = ["//watcher:__subpackages__"],
    deps = [
        "//proto/gen/telemetry",
        "//watcher/internal/config",
        "//watcher/internal/sender",
        "//watcher/pkg/kubernetes",
        "@com_github_rs_zerolog//log",
        "@io_k8s_api//core/v1:core",
        "@io_k8s_api//events/v1:events",
        "@io_k8s_apimachinery//pkg/fields",
        "@io_k8s_client_go//kubernetes",
        "@io_k8s_client_go//tools/cache",
    ],
)
