// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type L4FlowState struct {
	_         structs.HostLayout
	TsStartNs uint64
	TsEstabNs uint64
	BytesSent uint64
	BytesRecv uint64
	LastRttUs uint32
	Key       struct {
		_     structs.HostLayout
		Saddr uint32
		Daddr uint32
		Sport uint16
		Dport uint16
		Netns uint32
		Pid   uint32
	}
}

// LoadL4 returns the embedded CollectionSpec for L4.
func LoadL4() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_L4Bytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load L4: %w", err)
	}

	return spec, err
}

// LoadL4Objects loads L4 and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*L4Objects
//	*L4Programs
//	*L4Maps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadL4Objects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadL4()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// L4Specs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type L4Specs struct {
	L4ProgramSpecs
	L4MapSpecs
	L4VariableSpecs
}

// L4ProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type L4ProgramSpecs struct {
	K_tcpCleanupRbuf    *ebpf.ProgramSpec `ebpf:"k_tcp_cleanup_rbuf"`
	K_tcpRcvEstablished *ebpf.ProgramSpec `ebpf:"k_tcp_rcv_established"`
	K_tcpSendmsg        *ebpf.ProgramSpec `ebpf:"k_tcp_sendmsg"`
	TpInetSockSetState  *ebpf.ProgramSpec `ebpf:"tp_inet_sock_set_state"`
}

// L4MapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type L4MapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
	Flows  *ebpf.MapSpec `ebpf:"flows"`
}

// L4VariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type L4VariableSpecs struct {
}

// L4Objects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadL4Objects or ebpf.CollectionSpec.LoadAndAssign.
type L4Objects struct {
	L4Programs
	L4Maps
	L4Variables
}

func (o *L4Objects) Close() error {
	return _L4Close(
		&o.L4Programs,
		&o.L4Maps,
	)
}

// L4Maps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadL4Objects or ebpf.CollectionSpec.LoadAndAssign.
type L4Maps struct {
	Events *ebpf.Map `ebpf:"events"`
	Flows  *ebpf.Map `ebpf:"flows"`
}

func (m *L4Maps) Close() error {
	return _L4Close(
		m.Events,
		m.Flows,
	)
}

// L4Variables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadL4Objects or ebpf.CollectionSpec.LoadAndAssign.
type L4Variables struct {
}

// L4Programs contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadL4Objects or ebpf.CollectionSpec.LoadAndAssign.
type L4Programs struct {
	K_tcpCleanupRbuf    *ebpf.Program `ebpf:"k_tcp_cleanup_rbuf"`
	K_tcpRcvEstablished *ebpf.Program `ebpf:"k_tcp_rcv_established"`
	K_tcpSendmsg        *ebpf.Program `ebpf:"k_tcp_sendmsg"`
	TpInetSockSetState  *ebpf.Program `ebpf:"tp_inet_sock_set_state"`
}

func (p *L4Programs) Close() error {
	return _L4Close(
		p.K_tcpCleanupRbuf,
		p.K_tcpRcvEstablished,
		p.K_tcpSendmsg,
		p.TpInetSockSetState,
	)
}

func _L4Close(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed l4_bpfeb.o
var _L4Bytes []byte
