// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type L7RecvCtx struct {
	_        structs.HostLayout
	SkCookie uint64
	TsNs     uint64
	Len      uint32
	Flags    uint32
}

// LoadL7 returns the embedded CollectionSpec for L7.
func LoadL7() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_L7Bytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load L7: %w", err)
	}

	return spec, err
}

// LoadL7Objects loads L7 and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*L7Objects
//	*L7Programs
//	*L7Maps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadL7Objects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadL7()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// L7Specs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type L7Specs struct {
	L7ProgramSpecs
	L7MapSpecs
	L7VariableSpecs
}

// L7ProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type L7ProgramSpecs struct {
	KprobeTcpRecvmsgEnter *ebpf.ProgramSpec `ebpf:"kprobe_tcp_recvmsg_enter"`
	KprobeTcpSendmsg      *ebpf.ProgramSpec `ebpf:"kprobe_tcp_sendmsg"`
	KretTcpRecvmsg        *ebpf.ProgramSpec `ebpf:"kret_tcp_recvmsg"`
}

// L7MapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type L7MapSpecs struct {
	L7Events *ebpf.MapSpec `ebpf:"l7_events"`
	RecvMap  *ebpf.MapSpec `ebpf:"recv_map"`
}

// L7VariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type L7VariableSpecs struct {
}

// L7Objects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadL7Objects or ebpf.CollectionSpec.LoadAndAssign.
type L7Objects struct {
	L7Programs
	L7Maps
	L7Variables
}

func (o *L7Objects) Close() error {
	return _L7Close(
		&o.L7Programs,
		&o.L7Maps,
	)
}

// L7Maps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadL7Objects or ebpf.CollectionSpec.LoadAndAssign.
type L7Maps struct {
	L7Events *ebpf.Map `ebpf:"l7_events"`
	RecvMap  *ebpf.Map `ebpf:"recv_map"`
}

func (m *L7Maps) Close() error {
	return _L7Close(
		m.L7Events,
		m.RecvMap,
	)
}

// L7Variables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadL7Objects or ebpf.CollectionSpec.LoadAndAssign.
type L7Variables struct {
}

// L7Programs contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadL7Objects or ebpf.CollectionSpec.LoadAndAssign.
type L7Programs struct {
	KprobeTcpRecvmsgEnter *ebpf.Program `ebpf:"kprobe_tcp_recvmsg_enter"`
	KprobeTcpSendmsg      *ebpf.Program `ebpf:"kprobe_tcp_sendmsg"`
	KretTcpRecvmsg        *ebpf.Program `ebpf:"kret_tcp_recvmsg"`
}

func (p *L7Programs) Close() error {
	return _L7Close(
		p.KprobeTcpRecvmsgEnter,
		p.KprobeTcpSendmsg,
		p.KretTcpRecvmsg,
	)
}

func _L7Close(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed l7_bpfeb.o
var _L7Bytes []byte
