// Code generated by bpf2go; DO NOT EDIT.

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TcpMonitorStatsT struct {
	_           structs.HostLayout
	BytesSent   uint64
	SendCalls   uint64
	TotalSendNs uint64
	BytesRecv   uint64
	RecvCalls   uint64
	TotalRecvNs uint64
}

// LoadTcpMonitor returns the embedded CollectionSpec for TcpMonitor.
func LoadTcpMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TcpMonitor: %w", err)
	}

	return spec, err
}

// LoadTcpMonitorObjects loads TcpMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TcpMonitorObjects
//	*TcpMonitorPrograms
//	*TcpMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTcpMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTcpMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TcpMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpMonitorSpecs struct {
	TcpMonitorProgramSpecs
	TcpMonitorMapSpecs
	TcpMonitorVariableSpecs
}

// TcpMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpMonitorProgramSpecs struct {
	KprobeTcpRecvmsg    *ebpf.ProgramSpec `ebpf:"kprobe__tcp_recvmsg"`
	KprobeTcpSendmsg    *ebpf.ProgramSpec `ebpf:"kprobe__tcp_sendmsg"`
	KretprobeTcpRecvmsg *ebpf.ProgramSpec `ebpf:"kretprobe__tcp_recvmsg"`
	KretprobeTcpSendmsg *ebpf.ProgramSpec `ebpf:"kretprobe__tcp_sendmsg"`
}

// TcpMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpMonitorMapSpecs struct {
	StartTs  *ebpf.MapSpec `ebpf:"start_ts"`
	StatsMap *ebpf.MapSpec `ebpf:"stats_map"`
}

// TcpMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpMonitorVariableSpecs struct {
}

// TcpMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTcpMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpMonitorObjects struct {
	TcpMonitorPrograms
	TcpMonitorMaps
	TcpMonitorVariables
}

func (o *TcpMonitorObjects) Close() error {
	return _TcpMonitorClose(
		&o.TcpMonitorPrograms,
		&o.TcpMonitorMaps,
	)
}

// TcpMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTcpMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpMonitorMaps struct {
	StartTs  *ebpf.Map `ebpf:"start_ts"`
	StatsMap *ebpf.Map `ebpf:"stats_map"`
}

func (m *TcpMonitorMaps) Close() error {
	return _TcpMonitorClose(
		m.StartTs,
		m.StatsMap,
	)
}

// TcpMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTcpMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpMonitorVariables struct {
}

// TcpMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTcpMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpMonitorPrograms struct {
	KprobeTcpRecvmsg    *ebpf.Program `ebpf:"kprobe__tcp_recvmsg"`
	KprobeTcpSendmsg    *ebpf.Program `ebpf:"kprobe__tcp_sendmsg"`
	KretprobeTcpRecvmsg *ebpf.Program `ebpf:"kretprobe__tcp_recvmsg"`
	KretprobeTcpSendmsg *ebpf.Program `ebpf:"kretprobe__tcp_sendmsg"`
}

func (p *TcpMonitorPrograms) Close() error {
	return _TcpMonitorClose(
		p.KprobeTcpRecvmsg,
		p.KprobeTcpSendmsg,
		p.KretprobeTcpRecvmsg,
		p.KretprobeTcpSendmsg,
	)
}

func _TcpMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpmonitor_bpf.o
var _TcpMonitorBytes []byte
