// Code generated by bpf2go; DO NOT EDIT.

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type UProbesReqStatsT struct {
	_        structs.HostLayout
	ReqCount uint64
	TotalNs  uint64
}

// LoadUProbes returns the embedded CollectionSpec for UProbes.
func LoadUProbes() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_UProbesBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load UProbes: %w", err)
	}

	return spec, err
}

// LoadUProbesObjects loads UProbes and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*UProbesObjects
//	*UProbesPrograms
//	*UProbesMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadUProbesObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadUProbes()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// UProbesSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type UProbesSpecs struct {
	UProbesProgramSpecs
	UProbesMapSpecs
	UProbesVariableSpecs
}

// UProbesProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type UProbesProgramSpecs struct {
	UprobeHandlerEntry     *ebpf.ProgramSpec `ebpf:"uprobe__handler_entry"`
	UretprobeHandlerReturn *ebpf.ProgramSpec `ebpf:"uretprobe__handler_return"`
}

// UProbesMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type UProbesMapSpecs struct {
	ReqStart    *ebpf.MapSpec `ebpf:"req_start"`
	ReqStatsMap *ebpf.MapSpec `ebpf:"req_stats_map"`
}

// UProbesVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type UProbesVariableSpecs struct {
}

// UProbesObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadUProbesObjects or ebpf.CollectionSpec.LoadAndAssign.
type UProbesObjects struct {
	UProbesPrograms
	UProbesMaps
	UProbesVariables
}

func (o *UProbesObjects) Close() error {
	return _UProbesClose(
		&o.UProbesPrograms,
		&o.UProbesMaps,
	)
}

// UProbesMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadUProbesObjects or ebpf.CollectionSpec.LoadAndAssign.
type UProbesMaps struct {
	ReqStart    *ebpf.Map `ebpf:"req_start"`
	ReqStatsMap *ebpf.Map `ebpf:"req_stats_map"`
}

func (m *UProbesMaps) Close() error {
	return _UProbesClose(
		m.ReqStart,
		m.ReqStatsMap,
	)
}

// UProbesVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadUProbesObjects or ebpf.CollectionSpec.LoadAndAssign.
type UProbesVariables struct {
}

// UProbesPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadUProbesObjects or ebpf.CollectionSpec.LoadAndAssign.
type UProbesPrograms struct {
	UprobeHandlerEntry     *ebpf.Program `ebpf:"uprobe__handler_entry"`
	UretprobeHandlerReturn *ebpf.Program `ebpf:"uretprobe__handler_return"`
}

func (p *UProbesPrograms) Close() error {
	return _UProbesClose(
		p.UprobeHandlerEntry,
		p.UretprobeHandlerReturn,
	)
}

func _UProbesClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed uprobes_bpf.o
var _UProbesBytes []byte
