// Code generated by bpf2go; DO NOT EDIT.
//go:build linux

package http_metrics

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type http_metricsEndpointKey struct {
	_        structs.HostLayout
	CgroupId uint64
	Endpoint [128]int8
}

type http_metricsEndpointMetrics struct {
	_            structs.HostLayout
	RequestCount uint64
	ErrorCount   uint64
	LatencySum   uint64
	P95Latency   uint64
	LastUpdate   uint64
}

type http_metricsHttpMetrics struct {
	_            structs.HostLayout
	RequestCount uint64
	ErrorCount   uint64
	LatencySum   uint64
	LatencyMax   uint64
	LatencyMin   uint64
	Status2xx    uint64
	Status3xx    uint64
	Status4xx    uint64
	Status5xx    uint64
	LastUpdate   uint64
}

type http_metricsHttpRequest struct {
	_          structs.HostLayout
	StartTime  uint64
	CgroupId   uint64
	Pid        uint32
	StatusCode uint32
	Method     [16]int8
	Url        [256]int8
}

// loadHttp_metrics returns the embedded CollectionSpec for http_metrics.
func loadHttp_metrics() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Http_metricsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load http_metrics: %w", err)
	}

	return spec, err
}

// loadHttp_metricsObjects loads http_metrics and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*http_metricsObjects
//	*http_metricsPrograms
//	*http_metricsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadHttp_metricsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadHttp_metrics()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// http_metricsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type http_metricsSpecs struct {
	http_metricsProgramSpecs
	http_metricsMapSpecs
	http_metricsVariableSpecs
}

// http_metricsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type http_metricsProgramSpecs struct {
	TraceGoHttpEnd        *ebpf.ProgramSpec `ebpf:"trace_go_http_end"`
	TraceGoHttpStart      *ebpf.ProgramSpec `ebpf:"trace_go_http_start"`
	TraceHttpReadStart    *ebpf.ProgramSpec `ebpf:"trace_http_read_start"`
	TraceHttpRequestEnd   *ebpf.ProgramSpec `ebpf:"trace_http_request_end"`
	TraceHttpRequestStart *ebpf.ProgramSpec `ebpf:"trace_http_request_start"`
}

// http_metricsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type http_metricsMapSpecs struct {
	ActiveRequests     *ebpf.MapSpec `ebpf:"active_requests"`
	EndpointMetricsMap *ebpf.MapSpec `ebpf:"endpoint_metrics_map"`
	HttpEvents         *ebpf.MapSpec `ebpf:"http_events"`
	HttpMetricsMap     *ebpf.MapSpec `ebpf:"http_metrics_map"`
	LatencyHistogram   *ebpf.MapSpec `ebpf:"latency_histogram"`
	ReadFdTracker      *ebpf.MapSpec `ebpf:"read_fd_tracker"`
}

// http_metricsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type http_metricsVariableSpecs struct {
}

// http_metricsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadHttp_metricsObjects or ebpf.CollectionSpec.LoadAndAssign.
type http_metricsObjects struct {
	http_metricsPrograms
	http_metricsMaps
	http_metricsVariables
}

func (o *http_metricsObjects) Close() error {
	return _Http_metricsClose(
		&o.http_metricsPrograms,
		&o.http_metricsMaps,
	)
}

// http_metricsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadHttp_metricsObjects or ebpf.CollectionSpec.LoadAndAssign.
type http_metricsMaps struct {
	ActiveRequests     *ebpf.Map `ebpf:"active_requests"`
	EndpointMetricsMap *ebpf.Map `ebpf:"endpoint_metrics_map"`
	HttpEvents         *ebpf.Map `ebpf:"http_events"`
	HttpMetricsMap     *ebpf.Map `ebpf:"http_metrics_map"`
	LatencyHistogram   *ebpf.Map `ebpf:"latency_histogram"`
	ReadFdTracker      *ebpf.Map `ebpf:"read_fd_tracker"`
}

func (m *http_metricsMaps) Close() error {
	return _Http_metricsClose(
		m.ActiveRequests,
		m.EndpointMetricsMap,
		m.HttpEvents,
		m.HttpMetricsMap,
		m.LatencyHistogram,
		m.ReadFdTracker,
	)
}

// http_metricsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadHttp_metricsObjects or ebpf.CollectionSpec.LoadAndAssign.
type http_metricsVariables struct {
}

// http_metricsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadHttp_metricsObjects or ebpf.CollectionSpec.LoadAndAssign.
type http_metricsPrograms struct {
	TraceGoHttpEnd        *ebpf.Program `ebpf:"trace_go_http_end"`
	TraceGoHttpStart      *ebpf.Program `ebpf:"trace_go_http_start"`
	TraceHttpReadStart    *ebpf.Program `ebpf:"trace_http_read_start"`
	TraceHttpRequestEnd   *ebpf.Program `ebpf:"trace_http_request_end"`
	TraceHttpRequestStart *ebpf.Program `ebpf:"trace_http_request_start"`
}

func (p *http_metricsPrograms) Close() error {
	return _Http_metricsClose(
		p.TraceGoHttpEnd,
		p.TraceGoHttpStart,
		p.TraceHttpReadStart,
		p.TraceHttpRequestEnd,
		p.TraceHttpRequestStart,
	)
}

func _Http_metricsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed http_metrics_bpf.o
var _Http_metricsBytes []byte
