apiVersion: io.lumos/v1alpha1
kind: ServiceLevelObjective
metadata:
  name: checkout-service
spec:
  serviceName: checkout
  slo:
    latencyP95Ms: 200
    errorRatePercent: 1.0
    rps: 500
  priority: High
