apiVersion: v1
kind: Service
metadata:
  name: {{ include "futura-analytics.fullname" . }}
  labels:
    {{- include "futura-analytics.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "futura-analytics.selectorLabels" . | nindent 4 }}
