---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - opisvigilant.github.com
  resources:
  - futuras
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opisvigilant.github.com
  resources:
  - futuras/finalizers
  verbs:
  - update
- apiGroups:
  - opisvigilant.github.com
  resources:
  - futuras/status
  verbs:
  - get
  - patch
  - update
