[clickhouse]
servers = ["localhost:8123"]
database = "events"
username = "user"
password = "password"

[log]
level = "debug"

[recommender]
# some flags in the recommender are not exposed on porpuse
endpoint = "localhost:50053"
metricsFetcherInterval = "60" # in seconds 
checkpointsGCInterval = "600" # in seconds 
storage = "checkpoint"
historyLength = "8" # in days
historyResolution = "1" # in hours
queryTimeout = "5" # in minutes
