load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "dlq",
    srcs = [
        "dlq.go",
        "doc.go",
    ],
    importpath = "github.com/opisvigilant/futura/pipeline/internal/dlq",
    visibility = ["//pipeline:__subpackages__"],
    deps = [
        "//go-lib/stream",
        "//pipeline/internal/config",
        "@com_github_rs_zerolog//log",
    ],
)
