load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "secrets",
    srcs = [
        "aws.go",
        "gcp.go",
        "secrets.go",
    ],
    importpath = "github.com/opisvigilant/futura/apis/internal/secrets",
    visibility = ["//apis:__subpackages__"],
    deps = [
        "//apis/internal/config",
        "//proto/gen/backend",
        "@com_github_google_uuid//:uuid",
    ],
)
