syntax = "proto3";

package events;

option go_package = "github.com/opisvigilant/futura/proto/gen/events;events";

import "common/metadata.proto";

// Main batch message
message KubernetesEventBatch {
  common.APIKey apikey = 1;
  common.Metadata metadata = 2;
  repeated KubernetesEvent events = 3;
}

// Envelope for all possible event types
message KubernetesEvent {
  string object_kind = 1;
  string object_name = 2;
  string object_uid = 3;  
  string object_fieldpath = 4;
  int64 object_timestamp = 5;  // UNIX timestamp
  string object_namespace = 6;
  int64 event_severity_number = 7;
  string event_severity_text = 8;
  string event_reason = 9;
  string event_action = 10;
  string event_starttime = 11;
  string event_name = 12;
  string event_message = 13;
  string event_uid = 14;
  int64 event_count = 15;
  string object_api_version = 16;
  string object_resource_version = 17;
  string node_name = 18;
}