load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "replicaset",
    srcs = ["replicasets.go"],
    importpath = "github.com/opisvigilant/futura/watcher/internal/cluster/replicaset",
    visibility = ["//watcher:__subpackages__"],
    deps = [
        "//proto/gen/telemetry",
        "//watcher/internal/cluster/constants",
        "//watcher/internal/cluster/metadata",
        "@io_k8s_api//apps/v1:apps",
        "@org_golang_google_protobuf//types/known/timestamppb",
    ],
)
