syntax = "proto3";

package stats;

option go_package = "github.com/opisvigilant/futura/proto/gen/stats;stats";

import "common/metadata.proto";
import "google/protobuf/timestamp.proto";

message KubernetesKubeletStats {
  NodeStats node = 1;
  repeated PodStats pods = 2;

  common.APIKey apikey = 3;
  common.Metadata metadata = 4;

  EnrichmentMetadata enrichment = 100;
}

message EnrichmentMetadata {
  uint32 organization_id = 1;
  int64 cluster_id = 2;
  int64 received_at_unix = 3; // UNIX timestamp
}

message NodeStats {
  string nodeName = 1;
  repeated ContainerStats systemContainers = 2;
  google.protobuf.Timestamp startTime = 3;
  CPUStats cpu = 4;
  MemoryStats memory = 5;
  IOStats io = 6;
  NetworkStats network = 7;
  FsStats fs = 8;
  RuntimeStats runtime = 9;
  RlimitStats rlimit = 10;
  SwapStats swap = 11;
}

message RlimitStats {
  google.protobuf.Timestamp time = 1;
  int64 maxpid = 2;
  int64 numOfRunningProcesses = 3;
}

message RuntimeStats {
  FsStats imageFs = 1;
  FsStats containerFs = 2;
}

message PodStats {
  PodReference podRef = 1;
  google.protobuf.Timestamp startTime = 2;
  repeated ContainerStats containers = 3;
  CPUStats cpu = 4;
  MemoryStats memory = 5;
  IOStats io = 6;
  NetworkStats network = 7;
  repeated VolumeStats volumes = 8;
  FsStats ephemeralStorage = 9;
  ProcessStats processStats = 10;
  SwapStats swap = 11;
}

message ProcessStats { uint64 processCount = 1; }

message ContainerStats {
  string name = 1;
  google.protobuf.Timestamp startTime = 2;
  CPUStats cpu = 3;
  MemoryStats memory = 4;
  IOStats io = 5;
  repeated AcceleratorStats accelerators = 6;
  FsStats rootfs = 7;
  FsStats logs = 8;
  repeated UserDefinedMetric userDefinedMetrics = 9;
  SwapStats swap = 10;
}

message PodReference {
  string name = 1;
  string namespace = 2;
  string uid = 3;
}

message InterfaceStats {
  string name = 1;
  uint64 rxBytes = 2;
  uint64 rxErrors = 3;
  uint64 txBytes = 4;
  uint64 txErrors = 5;
}

message NetworkStats {
  google.protobuf.Timestamp time = 1;
  InterfaceStats interfaceStats = 2;
  repeated InterfaceStats interfaces = 3;
}

message CPUStats {
  google.protobuf.Timestamp time = 1;
  uint64 usageNanoCores = 2;
  uint64 usageCoreNanoSeconds = 3;
  PSIStats psi = 4;
}

message MemoryStats {
  google.protobuf.Timestamp time = 1;
  uint64 availableBytes = 2;
  uint64 usageBytes = 3;
  uint64 workingSetBytes = 4;
  uint64 rssBytes = 5;
  uint64 pageFaults = 6;
  uint64 majorPageFaults = 7;
  PSIStats psi = 8;
}

message IOStats {
  google.protobuf.Timestamp time = 1;
  PSIStats psi = 2;
}

message PSIStats {
  PSIData full = 1;
  PSIData some = 2;
}

message PSIData {
  uint64 total = 1;
  double avg10 = 2;
  double avg60 = 3;
  double avg300 = 4;
}

message SwapStats {
  google.protobuf.Timestamp time = 1;
  uint64 swapAvailableBytes = 2;
  uint64 swapUsageBytes = 3;
}

message AcceleratorStats {
  string make = 1;
  string model = 2;
  string id = 3;
  uint64 memoryTotal = 4;
  uint64 memoryUsed = 5;
  uint64 dutyCycle = 6;
}

message VolumeStats {
  FsStats fsStats = 1;
  string name = 2;
  PVCReference pvcRef = 3;
  VolumeHealthStats volumeHealthStats = 4;
}

message VolumeHealthStats { bool abnormal = 1; }

message PVCReference {
  string name = 1;
  string namespace = 2;
}

message FsStats {
  google.protobuf.Timestamp time = 1;
  uint64 availableBytes = 2;
  uint64 capacityBytes = 3;
  uint64 usedBytes = 4;
  uint64 inodesFree = 5;
  uint64 inodes = 6;
  uint64 inodesUsed = 7;
}

message UserDefinedMetricDescriptor {
  string name = 1;
  string type = 2;
  string units = 3;
  map<string, string> labels = 4;
}

message UserDefinedMetric {
  UserDefinedMetricDescriptor descriptor = 1;
  google.protobuf.Timestamp time = 2;
  double value = 3;
}