syntax = "proto3";

package stats;

option go_package = "github.com/opisvigilant/futura/proto/gen/stats;stats";

import "common/metadata.proto";

// Main batch message
message KubernetesEventBatch {
  common.APIKey apikey = 1;
  common.Metadata metadata = 2;
  repeated KubernetesResourceMetric resources = 3;
}

// ResourceMetric ties metrics to a resource.
message KubernetesResourceMetric {
  Resource resource = 1;
  MetricMetadata metric_metadata = 2;
  oneof metric_value {
    CPUMetrics cpu = 3;    
    MemoryMetrics memory = 4;
    FilesystemMetrics filesystem = 5;
    NetworkMetrics network = 6;
    VolumeMetrics volume = 7;
    UptimeMetrics uptime = 8;
  }
}

// Resource represents the metadata of the entity reporting the metrics.
message Resource {
  string kind = 1;              // Node, Pod, Container, etc.
  string name = 2;              // Name of the resource
  string namespace = 3;         // Namespace (if applicable)
  string uid = 4;               // Unique ID
  map<string, string> attributes = 5; // Extra tags/labels
}

// Metric represents a single metric datapoint.
message MetricMetadata {
  string name = 1;
  int64 timestamp = 2;
  string description = 3;
  map<string, string> labels = 4;
}

// Common CPU metrics
message CPUMetrics {
  int64 time = 1;
  double usage = 2;
  double utilization = 3;
  double node_utilization = 4;
  double limit_utilization = 5;
  double request_utilization = 6;
}

// Common Memory Metrics
message MemoryMetrics {
  int64 available = 1;
  int64 usage = 2;
  double node_utilization = 3;
  double limit_utilization = 4;
  double request_utilization = 5;
  int64 rss = 6;
  int64 working_set = 7;
  int64 page_faults = 8;
  int64 major_page_faults = 9;
}

// Filesystem Metrics
message FilesystemMetrics {
  int64 available = 1;
  int64 capacity = 2;
  int64 usage = 3;
}

// Network Metrics
message NetworkMetrics {
  int64 io = 1;
  int64 errors = 2;
}

// Volume Metrics
message VolumeMetrics {
  int64 available = 1;
  int64 capacity = 2;
  int64 inodes = 3;
  int64 inodes_free = 4;
  int64 inodes_used = 5;
}

// Uptime Metrics
message UptimeMetrics {
  int64 uptime = 1;
}
