load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "api",
    srcs = [
        "clusteroptimizationconfig_types.go",
        "groupversion_info.go",
        "servicelevelobjective_types.go",
        "zz_generated.deepcopy.go",
    ],
    importpath = "io.lumos/futura/api/v1",
    visibility = ["//visibility:public"],
    deps = [
        "@io_k8s_api//autoscaling/v2:autoscaling",
        "@io_k8s_api//core/v1:core",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/runtime",
        "@io_k8s_apimachinery//pkg/runtime/schema",
        "@io_k8s_autoscaler_vertical_pod_autoscaler//pkg/apis/autoscaling.k8s.io/v1:autoscaling_k8s_io",
        "@io_k8s_sigs_controller_runtime//pkg/scheme",
    ],
)
