load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "config",
    srcs = ["config.go"],
    importpath = "github.com/opisvigilant/futura/watcher/internal/config",
    visibility = ["//watcher:__subpackages__"],
    deps = [
        "@com_github_rs_zerolog//log",
        "@com_github_spf13_viper//:viper",
    ],
)
