apiVersion: v1
kind: ConfigMap
metadata:
  name: watcher-config
  namespace: default
  labels:
    app.kubernetes.io/name: watcher
    app.kubernetes.io/instance: watcher
data:
  config.toml: |
    # Configuration file running Watcher locally

    title = "Configuration for Watcher Kubernetes"

    debug = true
    nodeName = "locahost"
    tag = "v0.0.1"

    [collect]
    host = "localhost"
    port = "50051"

    [kubernetes]
    inCluster = true
