---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: watcher
rules:
  - apiGroups: [""]
    resources: ["pods", "replicationcontrollers"]
    verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: watcher
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: watcher
subjects:
  - kind: ServiceAccount
    name: watcher
    namespace: default
