---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: watcher
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: watcher
      app.kubernetes.io/instance: watcher
  template:
    metadata:
      labels:
        app.kubernetes.io/name: watcher
        app.kubernetes.io/instance: watcher
    spec:
      restartPolicy: Always
      serviceAccountName: watcher
      containers:
        - name: watcher
          image: ko://github.com/opisvigilant/futura/watcher
          securityContext:
            privileged: true
            capabilities:
              add:
                [
                  "SYS_ADMIN",
                  "SYS_RAWIO",
                  "SYS_RESOURCE",
                  "SYS_PTRACE",
                  "BPF",
                  "PERFMON",
                ]
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests: {}
          volumeMounts:
            - name: configuration
              mountPath: /opt/watcher/config.toml
              subPath: config.toml
            - name: sysfs
              mountPath: /sys/fs/cgroup
              readOnly: true
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: proc
              mountPath: /proc
              readOnly: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      volumes:
        - name: configuration
          configMap:
            name: watcher-config
        - name: sysfs
          hostPath:
            path: /sys/fs/cgroup
        - name: sys
          hostPath:
            path: /sys
        - name: proc
          hostPath:
            path: /proc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: watcher-config
  namespace: default
  labels:
    app.kubernetes.io/name: watcher
    app.kubernetes.io/instance: watcher
data:
  config.toml: |
    # Configuration file running Watcher locally
    [collect]
    endpoint = "host.docker.internal:50051"
    apiKey = "cluster_cc6VdWcwbdl5PNkHV2LEzxNZhXzQ246P"

    [kubernetes]
    namespaces = []
    distribution = "kubernetes" # either openshift or kubernetes
    objectsCollectionInterval = "" # in seconds, default is 10
    statsCollectionInterval = "" # in seconds, default is 20
    metadataCollectionInterval = "" # in minutes, default is 5
    leaseName = "futura" # required
    leaseNamespace = "default" # required
    leaseDuration = "" # in seconds, default is 15
    renewDeadline = "" # in seconds, default is 10
    retryPeriod = "" # in seconds, default is 2

    [kubernetes.auth]
    authType = "serviceAccount" # required, valid values are `none`, `serviceAccount`, `kubeConfig`
    kubeContextName = ""
    insecureSkipVerify = true
    kubeletCaFile = ""
    kubeletCertFile = ""
    kubeletKeyFile = ""

    [cloud]
    provider = "aws" # possible values: aws, azure, gcp, alibaba

    [log]
    level = "debug" # valid values: debug, info, warn, error
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: watcher
  namespace: default
  labels:
    app.kubernetes.io/name: watcher
    app.kubernetes.io/instance: watcher
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watcher
  namespace: default
  labels:
    app.kubernetes.io/name: watcher
    app.kubernetes.io/instance: watcher
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - namespaces
      - namespaces/status
      - nodes
      - nodes/spec
      - pods
      - pods/status
      - replicationcontrollers
      - replicationcontrollers/status
      - resourcequotas
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: [""]
    resources: ["nodes/stats"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["nodes/proxy"]
    verbs: ["get", "list"]
---
# Source: watcher/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: watcher
  namespace: default
  labels:
    app.kubernetes.io/name: watcher
    app.kubernetes.io/instance: watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: watcher
subjects:
  - kind: ServiceAccount
    name: watcher
    namespace: default
