// Code generated by bpf2go; DO NOT EDIT.
//go:build linux

package fs_tracker

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type fs_trackerFileAccess struct {
	_             structs.HostLayout
	FilePath      [256]int8
	AccessCount   uint64
	BytesAccessed uint64
	LatencyTotal  uint64
	AccessType    uint32
	_             [4]byte
	CgroupId      uint64
}

type fs_trackerFsMetrics struct {
	_                 structs.HostLayout
	ReadOps           uint64
	WriteOps          uint64
	OpenOps           uint64
	CloseOps          uint64
	SyncOps           uint64
	BytesRead         uint64
	BytesWritten      uint64
	ReadLatencyTotal  uint64
	WriteLatencyTotal uint64
	OpenLatencyTotal  uint64
	IoErrors          uint64
	PermissionErrors  uint64
	LastUpdate        uint64
}

type fs_trackerIoOperation struct {
	_         structs.HostLayout
	StartTime uint64
	CgroupId  uint64
	Pid       uint32
	OpType    uint32
	Fd        int32
	_         [4]byte
	Size      uint64
}

// loadFs_tracker returns the embedded CollectionSpec for fs_tracker.
func loadFs_tracker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Fs_trackerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load fs_tracker: %w", err)
	}

	return spec, err
}

// loadFs_trackerObjects loads fs_tracker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*fs_trackerObjects
//	*fs_trackerPrograms
//	*fs_trackerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFs_trackerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFs_tracker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// fs_trackerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fs_trackerSpecs struct {
	fs_trackerProgramSpecs
	fs_trackerMapSpecs
	fs_trackerVariableSpecs
}

// fs_trackerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fs_trackerProgramSpecs struct {
	TraceOpenatEnter *ebpf.ProgramSpec `ebpf:"trace_openat_enter"`
	TraceOpenatExit  *ebpf.ProgramSpec `ebpf:"trace_openat_exit"`
	TraceReadEnter   *ebpf.ProgramSpec `ebpf:"trace_read_enter"`
	TraceReadExit    *ebpf.ProgramSpec `ebpf:"trace_read_exit"`
	TraceWriteEnter  *ebpf.ProgramSpec `ebpf:"trace_write_enter"`
	TraceWriteExit   *ebpf.ProgramSpec `ebpf:"trace_write_exit"`
}

// fs_trackerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fs_trackerMapSpecs struct {
	FileAccessMap   *ebpf.MapSpec `ebpf:"file_access_map"`
	FsEvents        *ebpf.MapSpec `ebpf:"fs_events"`
	FsMetricsMap    *ebpf.MapSpec `ebpf:"fs_metrics_map"`
	IoOperationsMap *ebpf.MapSpec `ebpf:"io_operations_map"`
}

// fs_trackerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fs_trackerVariableSpecs struct {
}

// fs_trackerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFs_trackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type fs_trackerObjects struct {
	fs_trackerPrograms
	fs_trackerMaps
	fs_trackerVariables
}

func (o *fs_trackerObjects) Close() error {
	return _Fs_trackerClose(
		&o.fs_trackerPrograms,
		&o.fs_trackerMaps,
	)
}

// fs_trackerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFs_trackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type fs_trackerMaps struct {
	FileAccessMap   *ebpf.Map `ebpf:"file_access_map"`
	FsEvents        *ebpf.Map `ebpf:"fs_events"`
	FsMetricsMap    *ebpf.Map `ebpf:"fs_metrics_map"`
	IoOperationsMap *ebpf.Map `ebpf:"io_operations_map"`
}

func (m *fs_trackerMaps) Close() error {
	return _Fs_trackerClose(
		m.FileAccessMap,
		m.FsEvents,
		m.FsMetricsMap,
		m.IoOperationsMap,
	)
}

// fs_trackerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFs_trackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type fs_trackerVariables struct {
}

// fs_trackerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFs_trackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type fs_trackerPrograms struct {
	TraceOpenatEnter *ebpf.Program `ebpf:"trace_openat_enter"`
	TraceOpenatExit  *ebpf.Program `ebpf:"trace_openat_exit"`
	TraceReadEnter   *ebpf.Program `ebpf:"trace_read_enter"`
	TraceReadExit    *ebpf.Program `ebpf:"trace_read_exit"`
	TraceWriteEnter  *ebpf.Program `ebpf:"trace_write_enter"`
	TraceWriteExit   *ebpf.Program `ebpf:"trace_write_exit"`
}

func (p *fs_trackerPrograms) Close() error {
	return _Fs_trackerClose(
		p.TraceOpenatEnter,
		p.TraceOpenatExit,
		p.TraceReadEnter,
		p.TraceReadExit,
		p.TraceWriteEnter,
		p.TraceWriteExit,
	)
}

func _Fs_trackerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed fs_tracker_bpf.o
var _Fs_trackerBytes []byte
