-- eBPF Metrics Kafka Consumer Table
CREATE TABLE
    IF NOT EXISTS ebpf_metrics_kafka (
        -- Enrichment metadata
        organization_id UInt32,
        cluster_id Int64,
        k8s_version String,
        received_at_unix Int64,
        timestamp_unix Int64,
        -- Container context
        container_id String,
        pod_name String,
        pod_uid String,
        namespace String,
        node_name String,
        app_name String,
        app_version String,
        service_name String,
        cgroup_id UInt64,
        -- HTTP metrics
        http_request_count UInt64,
        http_error_count UInt64,
        http_error_rate Float64,
        http_latency_p50 Float64,
        http_latency_p95 Float64,
        http_latency_p99 Float64,
        -- Memory metrics
        memory_alloc_count UInt64,
        memory_free_count UInt64,
        memory_bytes_allocated UInt64,
        memory_bytes_freed UInt64,
        memory_net_allocated UInt64,
        memory_page_faults UInt64,
        memory_major_page_faults UInt64,
        memory_gc_count UInt64,
        memory_gc_time_us UInt64,
        -- CPU metrics
        cpu_user_time_us UInt64,
        cpu_system_time_us UInt64,
        cpu_utilization Float64,
        cpu_context_switches UInt64,
        cpu_voluntary_switches UInt64,
        cpu_involuntary_switches UInt64,
        cpu_runqueue_latency_us Float64,
        cpu_active_threads UInt32,
        cpu_blocked_threads UInt32,
        -- Network metrics
        network_bytes_sent UInt64,
        network_bytes_received UInt64,
        network_packets_sent UInt64,
        network_packets_received UInt64,
        network_connections_established UInt64,
        network_connections_closed UInt64,
        network_connection_failures UInt64,
        network_avg_rtt_us Float64,
        -- File system metrics
        fs_read_ops UInt64,
        fs_write_ops UInt64,
        fs_bytes_read UInt64,
        fs_bytes_written UInt64,
        fs_read_latency_p95_us Float64,
        fs_write_latency_p95_us Float64,
        fs_read_bandwidth_mbps Float64,
        fs_write_bandwidth_mbps Float64,
        -- Application metrics
        app_db_query_count UInt64,
        app_db_slow_queries UInt64,
        app_cache_hit_rate Float64,
        app_gc_count UInt64,
        app_gc_time_us UInt64,
        -- Security metrics
        security_anomalous_count UInt64,
        security_privilege_escalation_count UInt64,
        security_suspicious_connection_count UInt64,
        security_suspicious_process_count UInt64,
        security_unauthorized_access_count UInt64
    ) ENGINE = Kafka SETTINGS kafka_broker_list = 'kafka1:9092',
    kafka_topic_list = 'store.ebpf.metrics',
    kafka_group_name = 'clickhouse-ebpf-consumer',
    kafka_format = 'JSONEachRow',
    kafka_num_consumers = 1,
    kafka_thread_per_consumer = 1;

-- eBPF Metrics Main Table (MergeTree)
CREATE TABLE
    IF NOT EXISTS ebpf_metrics (
        -- Enrichment metadata
        organization_id UInt32,
        cluster_id Int64,
        k8s_version String,
        received_at_unix Int64,
        timestamp DateTime64 (3),
        -- Container context
        container_id String,
        pod_name String,
        pod_uid String,
        namespace String,
        node_name String,
        app_name String,
        app_version String,
        service_name String,
        cgroup_id UInt64,
        -- HTTP metrics
        http_request_count UInt64,
        http_error_count UInt64,
        http_error_rate Float64,
        http_latency_p50 Float64,
        http_latency_p95 Float64,
        http_latency_p99 Float64,
        -- Memory metrics
        memory_alloc_count UInt64,
        memory_free_count UInt64,
        memory_bytes_allocated UInt64,
        memory_bytes_freed UInt64,
        memory_net_allocated UInt64,
        memory_page_faults UInt64,
        memory_major_page_faults UInt64,
        memory_gc_count UInt64,
        memory_gc_time_us UInt64,
        -- CPU metrics
        cpu_user_time_us UInt64,
        cpu_system_time_us UInt64,
        cpu_utilization Float64,
        cpu_context_switches UInt64,
        cpu_voluntary_switches UInt64,
        cpu_involuntary_switches UInt64,
        cpu_runqueue_latency_us Float64,
        cpu_active_threads UInt32,
        cpu_blocked_threads UInt32,
        -- Network metrics
        network_bytes_sent UInt64,
        network_bytes_received UInt64,
        network_packets_sent UInt64,
        network_packets_received UInt64,
        network_connections_established UInt64,
        network_connections_closed UInt64,
        network_connection_failures UInt64,
        network_avg_rtt_us Float64,
        -- File system metrics
        fs_read_ops UInt64,
        fs_write_ops UInt64,
        fs_bytes_read UInt64,
        fs_bytes_written UInt64,
        fs_read_latency_p95_us Float64,
        fs_write_latency_p95_us Float64,
        fs_read_bandwidth_mbps Float64,
        fs_write_bandwidth_mbps Float64,
        -- Application metrics
        app_db_query_count UInt64,
        app_db_slow_queries UInt64,
        app_cache_hit_rate Float64,
        app_gc_count UInt64,
        app_gc_time_us UInt64,
        -- Security metrics
        security_anomalous_count UInt64,
        security_privilege_escalation_count UInt64,
        security_suspicious_connection_count UInt64,
        security_suspicious_process_count UInt64,
        security_unauthorized_access_count UInt64
    ) ENGINE = ReplacingMergeTree
PARTITION BY
    toYYYYMM (timestamp)
ORDER BY
    (
        organization_id,
        cluster_id,
        container_id,
        timestamp
    );

-- Materialized View to consume from Kafka
CREATE MATERIALIZED VIEW IF NOT EXISTS mv_ebpf_metrics TO ebpf_metrics AS
SELECT
    organization_id,
    cluster_id,
    k8s_version,
    received_at_unix,
    fromUnixTimestamp64Milli (timestamp_unix * 1000) AS timestamp,
    container_id,
    pod_name,
    pod_uid,
    namespace,
    node_name,
    app_name,
    app_version,
    service_name,
    cgroup_id,
    http_request_count,
    http_error_count,
    http_error_rate,
    http_latency_p50,
    http_latency_p95,
    http_latency_p99,
    memory_alloc_count,
    memory_free_count,
    memory_bytes_allocated,
    memory_bytes_freed,
    memory_net_allocated,
    memory_page_faults,
    memory_major_page_faults,
    memory_gc_count,
    memory_gc_time_us,
    cpu_user_time_us,
    cpu_system_time_us,
    cpu_utilization,
    cpu_context_switches,
    cpu_voluntary_switches,
    cpu_involuntary_switches,
    cpu_runqueue_latency_us,
    cpu_active_threads,
    cpu_blocked_threads,
    network_bytes_sent,
    network_bytes_received,
    network_packets_sent,
    network_packets_received,
    network_connections_established,
    network_connections_closed,
    network_connection_failures,
    network_avg_rtt_us,
    fs_read_ops,
    fs_write_ops,
    fs_bytes_read,
    fs_bytes_written,
    fs_read_latency_p95_us,
    fs_write_latency_p95_us,
    fs_read_bandwidth_mbps,
    fs_write_bandwidth_mbps,
    app_db_query_count,
    app_db_slow_queries,
    app_cache_hit_rate,
    app_gc_count,
    app_gc_time_us,
    security_anomalous_count,
    security_privilege_escalation_count,
    security_suspicious_connection_count,
    security_suspicious_process_count,
    security_unauthorized_access_count
FROM
    ebpf_metrics_kafka;