// Code generated by bpf2go; DO NOT EDIT.
//go:build linux

package app_specific

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type app_specificCacheMetrics struct {
	_               structs.HostLayout
	CacheHits       uint64
	CacheMisses     uint64
	CacheSets       uint64
	CacheGets       uint64
	CacheDeletes    uint64
	CacheEvictions  uint64
	GetLatencyTotal uint64
	SetLatencyTotal uint64
	CacheSizeBytes  uint64
	LastUpdate      uint64
}

type app_specificDbMetrics struct {
	_                    structs.HostLayout
	QueryCount           uint64
	QueryTimeTotal       uint64
	SlowQueries          uint64
	ActiveConnections    uint64
	ConnectionTimeouts   uint64
	Transactions         uint64
	Rollbacks            uint64
	TransactionTimeTotal uint64
	LastUpdate           uint64
}

type app_specificFunctionTiming struct {
	_            structs.HostLayout
	StartTime    uint64
	CgroupId     uint64
	Pid          uint32
	FunctionName [128]int8
	_            [4]byte
}

type app_specificGoMetrics struct {
	_                  structs.HostLayout
	Goroutines         uint64
	GoroutineStackSize uint64
	GcCycles           uint64
	GcPauseTimeUs      uint64
	HeapSize           uint64
	HeapAlloc          uint64
	HeapIdle           uint64
	ChannelSends       uint64
	ChannelReceives    uint64
	BlockedChannels    uint64
	LastUpdate         uint64
}

// loadApp_specific returns the embedded CollectionSpec for app_specific.
func loadApp_specific() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_App_specificBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load app_specific: %w", err)
	}

	return spec, err
}

// loadApp_specificObjects loads app_specific and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*app_specificObjects
//	*app_specificPrograms
//	*app_specificMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadApp_specificObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadApp_specific()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// app_specificSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type app_specificSpecs struct {
	app_specificProgramSpecs
	app_specificMapSpecs
	app_specificVariableSpecs
}

// app_specificProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type app_specificProgramSpecs struct {
	TraceCacheGetEnd   *ebpf.ProgramSpec `ebpf:"trace_cache_get_end"`
	TraceCacheGetStart *ebpf.ProgramSpec `ebpf:"trace_cache_get_start"`
	TraceCustomMetric  *ebpf.ProgramSpec `ebpf:"trace_custom_metric"`
	TraceDbQueryEnd    *ebpf.ProgramSpec `ebpf:"trace_db_query_end"`
	TraceDbQueryStart  *ebpf.ProgramSpec `ebpf:"trace_db_query_start"`
	TraceGoGcEnd       *ebpf.ProgramSpec `ebpf:"trace_go_gc_end"`
	TraceGoGcStart     *ebpf.ProgramSpec `ebpf:"trace_go_gc_start"`
}

// app_specificMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type app_specificMapSpecs struct {
	AppEvents          *ebpf.MapSpec `ebpf:"app_events"`
	CacheMetricsMap    *ebpf.MapSpec `ebpf:"cache_metrics_map"`
	DbMetricsMap       *ebpf.MapSpec `ebpf:"db_metrics_map"`
	FunctionTimingsMap *ebpf.MapSpec `ebpf:"function_timings_map"`
	GoMetricsMap       *ebpf.MapSpec `ebpf:"go_metrics_map"`
}

// app_specificVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type app_specificVariableSpecs struct {
}

// app_specificObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadApp_specificObjects or ebpf.CollectionSpec.LoadAndAssign.
type app_specificObjects struct {
	app_specificPrograms
	app_specificMaps
	app_specificVariables
}

func (o *app_specificObjects) Close() error {
	return _App_specificClose(
		&o.app_specificPrograms,
		&o.app_specificMaps,
	)
}

// app_specificMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadApp_specificObjects or ebpf.CollectionSpec.LoadAndAssign.
type app_specificMaps struct {
	AppEvents          *ebpf.Map `ebpf:"app_events"`
	CacheMetricsMap    *ebpf.Map `ebpf:"cache_metrics_map"`
	DbMetricsMap       *ebpf.Map `ebpf:"db_metrics_map"`
	FunctionTimingsMap *ebpf.Map `ebpf:"function_timings_map"`
	GoMetricsMap       *ebpf.Map `ebpf:"go_metrics_map"`
}

func (m *app_specificMaps) Close() error {
	return _App_specificClose(
		m.AppEvents,
		m.CacheMetricsMap,
		m.DbMetricsMap,
		m.FunctionTimingsMap,
		m.GoMetricsMap,
	)
}

// app_specificVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadApp_specificObjects or ebpf.CollectionSpec.LoadAndAssign.
type app_specificVariables struct {
}

// app_specificPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadApp_specificObjects or ebpf.CollectionSpec.LoadAndAssign.
type app_specificPrograms struct {
	TraceCacheGetEnd   *ebpf.Program `ebpf:"trace_cache_get_end"`
	TraceCacheGetStart *ebpf.Program `ebpf:"trace_cache_get_start"`
	TraceCustomMetric  *ebpf.Program `ebpf:"trace_custom_metric"`
	TraceDbQueryEnd    *ebpf.Program `ebpf:"trace_db_query_end"`
	TraceDbQueryStart  *ebpf.Program `ebpf:"trace_db_query_start"`
	TraceGoGcEnd       *ebpf.Program `ebpf:"trace_go_gc_end"`
	TraceGoGcStart     *ebpf.Program `ebpf:"trace_go_gc_start"`
}

func (p *app_specificPrograms) Close() error {
	return _App_specificClose(
		p.TraceCacheGetEnd,
		p.TraceCacheGetStart,
		p.TraceCustomMetric,
		p.TraceDbQueryEnd,
		p.TraceDbQueryStart,
		p.TraceGoGcEnd,
		p.TraceGoGcStart,
	)
}

func _App_specificClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed app_specific_bpf.o
var _App_specificBytes []byte
