syntax = "proto3";

package backend;

option go_package = "github.com/opisvigilant/futura/proto/gen/backend;backend";

enum UserStatus {
  UNDEFINED_USER_STATUS = 0;
  USER_ACTIVE = 1;
  USER_INVITED = 2;
  USER_INACTIVE = 3;
}

enum UserRole {
  UNDEFINED_USER_ROLE = 0;
  USER_ADMIN = 1;
  USER_MANAGER = 2;
  USER_DEVELOPER = 3;
  USER_VIEWER = 4;
}

message User {
  int64 id = 1;
  string first_name = 2;
  string last_name = 3;
  string email = 4;
  UserRole role = 5;
  repeated string teams = 6;
  string created_at = 7;
  string last_access = 8;
  UserStatus status = 9;
  string avatar = 10;
  string provider = 11;
}

message GetUsersResponse {
  repeated User users = 1;
}

message InviteUserRequest {
  string first_name = 1;
  string last_name = 2;
  string email = 3;
  UserRole role = 4;
  repeated int64 team_ids = 5;
}

message UpdateUserRequest {
  string first_name = 1;
  string last_name = 2;
  string email = 3;
  UserRole role = 4;
  repeated int64 team_ids = 5;
  UserStatus status = 6;
}
